def vista():
    import xbmc
    skin_name=xbmc.getSkinDir()
    ALL_VIEW_CODES = {'list': {'default_files': 50,
                                   'movies': 515,
                                   'tvshows': 508,
                                   'seasons': 503,
                                   'episodes': 504,
                                   'view_list': 50,
                                   'view_poster': 51,
                                   'view_thumbnails': 500,
                                   'view_movie_with_plot': 56},
                     'skin.aeon.nox.silvo': {'default_files': 50,
                                             'movies': 515,
                                             'tvshows': 508,
                                             'seasons': 503,
                                             'episodes': 504,
                                             'view_list': 50,
                                             'view_poster': 509,
                                             'view_thumbnails': 500,
                                             'view_movie_with_plot': 51},
                     'skin.aeon.tajo': {'default_files': 50,
                                        'movies': 515,
                                        'tvshows': 508,
                                        'seasons': 503,
                                        'episodes': 504,
                                        'view_list': 50,
                                        'view_poster': 595,
                                        'view_thumbnails': 500,
                                        'view_movie_with_plot': 590},
                     'skin.amber': {'default_files': 50,
                                    'movies': 515,
                                    'tvshows': 508,
                                    'seasons': 503,
                                    'episodes': 504,
                                    'view_list': 50,
                                    'view_poster': 56,
                                    'view_thumbnails': 500,
                                    'view_movie_with_plot': 551},
                     'skin.apptv': {'default_files': 50,
                                    'movies': 515,
                                    'tvshows': 508,
                                    'seasons': 503,
                                    'episodes': 504,
                                    'view_list': 50,
                                    'view_poster': 54,
                                    'view_thumbnails': 500,
                                    'view_movie_with_plot': 58},
                     'skin.bello.7': {'default_files': 50,
                                  'movies': 515,
                                  'tvshows': 508,
                                  'seasons': 503,
                                  'episodes': 504,
                                  'view_list': 50,
                                  'view_poster': 66,
                                  'view_thumbnails': 500,
                                  'view_movie_with_plot': 50},
                     'skin.box': {'default_files': 50,
                                  'movies': 515,
                                  'tvshows': 508,
                                  'seasons': 503,
                                  'episodes': 504,
                                  'view_list': 50,
                                  'view_poster': 532,
                                  'view_thumbnails': 500,
                                  'view_movie_with_plot': 58},
                                  
                     'skin.confluence-chopo': {'default_files': 50,
                                         'movies': 503,
                                         'tvshows': 502,
                                         'seasons': 503,
                                         'episodes': 504,
                                         'view_list': 50,
                                         'view_poster': 503,
                                         'view_thumbnails': 500,
                                         'view_movie_with_plot': 504},                                  
                                  
                     'skin.confluence': {'default_files': 50,
                                         'movies': 503,
                                         'tvshows': 508,
                                         'seasons': 503,
                                         'episodes': 504,
                                         'view_list': 50,
                                         'view_poster': 503,
                                         'view_thumbnails': 500,
                                         'view_movie_with_plot': 504},
                     'skin.embuary-leia': {'default_files': 50,
                                         'movies': 515,
                                         'tvshows': 508,
                                         'seasons': 503,
                                         'episodes': 504,
                                         'view_list': 50,
                                         'view_poster': 56,
                                         'view_thumbnails': 500,
                                         'view_movie_with_plot': 51},
                     'skin.eminence.2': {'default_files': 50,
                                         'movies': 515,
                                         'tvshows': 508,
                                         'seasons': 503,
                                         'episodes': 504,
                                         'view_list': 50,
                                         'view_poster': 52,
                                         'view_thumbnails': 500,
                                         'view_movie_with_plot': 59},
                     'skin.estuary': {'default_files': 50,
                                      'movies': 54,
                                      'tvshows': 502,
                                      'seasons': 500,
                                      'episodes': 53,
                                      'view_list': 50,
                                      'view_poster': 51,
                                      'view_thumbnails': 500,
                                      'view_movie_with_plot': 54},
                     'skin.ftv': {'default_files': 50,
                                  'movies': 515,
                                  'tvshows': 508,
                                  'seasons': 503,
                                  'episodes': 504,
                                  'view_list': 50,
                                  'view_poster': 57,
                                  'view_thumbnails': 500,
                                  'view_movie_with_plot': 57},
                     'skin.madnox': {'default_files': 50,
                                     'movies': 515,
                                     'tvshows': 508,
                                     'seasons': 503,
                                     'episodes': 504,
                                     'view_list': 50,
                                     'view_poster': 510,
                                     'view_thumbnails': 500,
                                     'view_movie_with_plot': 530},
                     'skin.quartz': {'default_files': 50,
                                     'movies': 515,
                                     'tvshows': 508,
                                     'seasons': 503,
                                     'episodes': 504,
                                     'view_list': 50,
                                     'view_poster': 501,
                                     'view_thumbnails': 500,
                                     'view_movie_with_plot': 502},
                     'skin.rapier': {'default_files': 50,
                                     'movies': 515,
                                     'tvshows': 508,
                                     'seasons': 503,
                                     'episodes': 504,
                                     'view_list': 50,
                                     'view_poster': 53,
                                     'view_thumbnails': 500,
                                     'view_movie_with_plot': 97},
                     'skin.revolve': {'default_files': 50,
                                      'movies': 515,
                                      'tvshows': 508,
                                      'seasons': 503,
                                      'episodes': 504,
                                      'view_list': 50,
                                      'view_poster': 53,
                                      'view_thumbnails': 500,
                                      'view_movie_with_plot': 58},
                     'skin.transparency': {'default_files': 50,
                                           'movies': 515,
                                           'tvshows': 508,
                                           'seasons': 503,
                                           'episodes': 504,
                                           'view_list': 50,
                                           'view_poster': 55,
                                           'view_thumbnails': 500,
                                           'view_movie_with_plot': 58},
                     'skin.default': {'default_files': 50,
                                      'movies': 515,
                                      'tvshows': 508,
                                      'seasons': 503,
                                      'episodes': 504,
                                      'view_list': 50,
                                      'view_poster': 55,
                                      'view_thumbnails': 500,
                                      'view_movie_with_plot': 501}}


    return[ALL_VIEW_CODES]